version: "3"
services:
  web:
    build: .
    image: cutly
    container_name: "cutly"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db/cutly
    ports:
    - "27017:27017"

